# ros2
export ROS_DOMAIN_ID=11
source /opt/ros/humble/setup.bash

# colcon
source /usr/share/colcon_cd/function/colcon_cd.sh
export _colcon_cd_root=/opt/ros/humble/
source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash
